---
title: "About"
---

My experience growing up in the wildland urban interface outside of Colorado Springs, Colorado shaped my love for and interest in the natural world. I spent the majority of my childhood outside in a ponderosa pine forest in Black Forest, an unincorporated area to the northeast of the Springs. In 2013, a fire came through this area, burning down my family's home along with around 500 other structures. I saw firsthand how the legacy of fire exclusion, forest mismanagement, and climate change impacts people first hand, and the inequal way these impacts are felt across different socioeconomic groups. These experiences drove my interest in fire science as well as climate justice.

I completed my undergraduate degree at Colorado State University in Forest and Rangeland Stewardship in Spring of 2025. During this time, I worked for the USFS as a Forestry Research Technician and Biogeochemical Lab Technician, gaining experience in both a field and laboratory setting. I also participated in the campus chapter of the Society of American Foresters, serving as the very first Diversity and Outreach Chair for the club.

Starting in Fall 2025, I am pursuing a Masters degree in Forest Sciences as a member of the Francis Forest Ecology Lab. Here, I am working on a project with a larger group using Aerial LIDAR to characterize forest structure in order to model potential fire behavior across different ecosystems.
